const gettingReady = [
  { e: 'bathrobe', s: 'bata', g: 'f' },
  { e: 'slippers', s: 'pantuflas', g: 'f', p: true },
  { e: 'hairbrush', s: 'cepillo', g: 'm' },
  { e: 'comb', s: 'peine', g: 'm' },
  { e: 'toothbrush', s: 'cepillo de dientes', g: 'm' },
  { e: 'toothpaste', s: 'pasta de dientes', g: 'f' },
  { e: 'deoderant', s: 'desodorante', g: 'm' },
  { e: 'razor', s: 'rasurador', g: 'm' },
  { e: 'body lotion', s: 'crema', g: 'f' },
  { e: 'perfume', s: 'loción', g: 'f' },
  { e: 'shampoo', s: 'champú', g: 'm' },
  { e: 'soap', s: 'jabón', g: 'm' },
  { e: 'maquillaje', s: 'makeup', g: 'm' },
  { e: 'mirror', s: 'espejo', g: 'm' },
  { e: 'towel', s: 'toalla', g: 'f' },
  { e: 'alarm clock', s: 'reloj despertador', g: 'm' },
];

const placesAndEvents = [
  { e: 'country', s: 'campo', g: 'm' },
  { e: 'zoo', s: 'zoológico', g: 'm' },
  { e: 'city', s: 'cuidad', g: 'f' },
  { e: 'amusement park', s: 'parque de atracciones', g: 'm' },
  { e: 'circus', s: 'circo', g: 'm' },
  { e: 'theater', s: 'teatro', g: 'm' },
  { e: 'aquarium', s: 'acuario', g: 'm' },
  { e: 'museum', s: 'museo', g: 'm' },
  { e: 'lake', s: 'lago', g: 'm' },
  { e: 'anniversary party', s: 'fiesta de aniversario', g: 'f' },
  { e: 'graduation party', s: 'fiesta de graduación', g: 'f' },
  { e: 'birthday party', s: 'fiesta de cumpleaños', g: 'f' },
  { e: 'surprise party', s: 'fiesta de sorpresa', g: 'f' },
  { e: 'baby shower', s: 'fiesta de bienvenida', g: 'f' },
];

const thanksgiving = [
  { e: 'apple', s: 'manzana', g: 'f' },
  { e: 'turkey', s: 'pavo', g: 'm' },
  { e: 'corn', s: 'maíz', g: 'm' },
  { e: 'vegetables', s: 'legumbres', g: 'm', p: true },
  { e: 'meat sauce', s: 'salsa de carne', g: 'f' },
  { e: 'stuffing', s: 'relleno', g: 'm' },
  { e: 'mashed potatoes', s: 'puré de papas', g: 'm' },
  { e: 'apple pie', s: 'torta de manzana', g: 'f' },
  { e: 'pumpkin pie', s: 'torta de calbaza', g: 'f' },
  { e: 'dinner', s: 'cena', g: 'f' },
  { e: 'rolls', s: 'panecillos', g: 'm' },
];

const stemChangingVerbs = [
  { e: 'have lunch', s: 'almorzar', c: ['almuerzo', 'almuerzas', 'almuerza', 'almorzamos', 'almuerzan'] },
  { e: 'close', s: 'cerrar', c: ['cierro', 'cierras', 'cierra', 'ceramos', 'cierran'] },
  { e: 'say', s: 'decir', c: ['digo', 'dices', 'dice', 'decimos', 'dicen'] },
  { e: 'sleep', s: 'dormir', c: ['duermo', 'duermes', 'duerme', 'dormimos', 'duermen'] },
  { e: 'find', s: 'encontrar', c: ['encuentro', 'encuentras', 'encuentra', 'encontramos', 'encuentren'] },
  { e: 'bite', s: 'morder', c: ['muerdo', 'muerdes', 'muerde', 'mordemos', 'muerden'] },
  { e: 'plan', s: 'pensar', c: ['pienso', 'piensas', 'piensa', 'pensamos', 'piensan'] },
  { e: 'be able', s: 'poder', c: ['puedo', 'puedes', 'puede', 'podemos', 'pueden'] },
  { e: 'play', s: 'jugar', c: ['juego', 'juegas', 'juega', 'jugamos', 'juegan'] },
  { e: 'want', s: 'querer', c: ['quiero', 'quieres', 'quiere', 'queremos', 'quieren'] },
  { e: 'feel', s: 'sentir', c: ['siento', 'sientes', 'siente', 'sentimos', 'sienten'] },
  { e: 'come', s: 'venir', c: ['vengo', 'vienes', 'viene', 'venimos', 'vienen'] },
];

const irregularVerbs = [
  { e: 'fall', s: 'caer', c: ['caigo', 'caes', 'cae', 'caemos', 'caen'] },
  { e: 'know / meet', s: 'conocer', c: ['conozco', 'conoces', 'conoce', 'conocemos', 'conocen'] },
  { e: 'give', s: 'dar', c: ['doy', 'das', 'da', 'damos', 'dan'] },
  { e: 'ski', s: 'esquiar', c: ['esquío', 'esquías', 'esquía', 'esquiamos', 'esqúian'] },
  { e: 'be', s: 'estar', c: ['estoy', 'estás', 'está', 'estamos', 'están'] },
  { e: 'do', s: 'hacer', c: ['hago', 'haces', 'hace', 'hacemos', 'hacen'] },
  { e: 'go', s: 'ir', c: ['voy', 'vas', 'va', 'vamos', 'van'] },
  { e: 'put', s: 'poner', c: ['pongo', 'pones', 'pone', 'ponemos', 'ponen'] },
  { e: 'know / taste', s: 'sabor', c: ['sé', 'sabes', 'sabe', 'sabemos', 'saben'] },
  { e: 'go out', s: 'salir', c: ['salgo', 'sales', 'sale', 'salimos', 'salen'] },
  { e: 'bring', s: 'traer', c: ['traigo', 'traes', 'trae', 'traemos', 'traen'] },
  { e: 'see', s: 'ver', c: ['veo', 'ves', 've', 'vemos', 'ven'] },
];

const standardVerbs = [
  { e: 'open', s: 'abrir', c: ['abro', 'abres', 'abre', 'abremos', 'abren'] },
  { e: 'finish', s: 'acabar', c: ['acabo', 'acabas', 'acaba', 'acabamos', 'acaban'] },
  { e: 'camp', s: 'acampar', c: ['acampo', 'acampas', 'acampa', 'acampamos', 'acampan'] },
  { e: 'help', s: 'ayudar', c: ['ayudo', 'ayudas', 'ayuda', 'ayudamos', 'ayudan'] },
  { e: 'dance', s: 'bailar', c: ['bailo', 'bailas', 'baila', 'bailamos', 'bailan'] },
  { e: 'drink', s: 'beber', c: ['bebo', 'bebes', 'bebe', 'bebemos', 'beben'] },
  { e: 'kiss', s: 'besar', c: ['beso', 'besas', 'besa', 'besamos', 'besan'] },
  { e: 'scuba dive', s: 'bucear', c: ['buceo', 'buceas', 'bucea', 'buceamos', 'bucean'] },
  { e: 'look for', s: 'buscar', c: ['busco', 'buscas', 'busca', 'buscamos', 'buscan'] },
  { e: 'walk', s: 'caminar', c: ['camino', 'caminas', 'camina', 'caminamos', 'caminan'] },
  { e: 'sing', s: 'cantar', c: ['canto', 'cantas', 'canta', 'cantamos', 'cantan'] },
  { e: 'have dinner', s: 'cenar', c: ['ceno', 'cenas', 'cena', 'cenamos', 'cenan'] },
  { e: 'eat', s: 'comer', c: ['como', 'comes', 'come', 'comemos', 'comen'] },
  { e: 'buy', s: 'comprar', c: ['compro', 'compras', 'compra', 'compramos', 'compran'] },
  { e: 'sing', s: 'cantar', c: ['canto', 'cantas', 'canta', 'cantamos', 'cantan'] },
  { e: 'cook', s: 'cocinar', c: ['cocino', 'cocinas', 'cocina', 'cocinamos', 'cocinan'] },
  { e: 'run', s: 'correr', c: ['corro', 'corres', 'corre', 'corremos', 'corren'] },
  { e: 'take care of', s: 'cuidar', c: ['cuido', 'cuidas', 'cuida', 'cuidamos', 'cuidan']},
  { e: 'owe', s: 'deber', c: ['debo', 'debes', 'debe', 'debemos', 'deben'] },
  { e: 'have breakfast', s: 'desayunar', c: ['desayuno', 'desayunas', 'desayuna', 'desayunamos', 'desayunan'] },
  { e: 'rest', s: 'descansar', c: ['descanso', 'descansas', 'descansa', 'descansamos', 'descansan'] },
  { e: 'draw', s: 'dibujar', c: ['dibujo', 'dibujas', 'dibuja', 'dibujamos', 'dibujan'] },
  { e: 'enter', s: 'entrar', c: ['entro', 'entras', 'entra', 'entramos', 'entran'] },
  { e: 'write', s: 'escribir', c: ['escribo', 'escribes', 'escribe', 'escribimos', 'escriben'] },
  { e: 'hide', s: 'esconder', c: ['escondo', 'escondes', 'esconde', 'escondemos', 'esconden'] },
  { e: 'listen', s: 'escuchar', c: ['escucho', 'escuchas', 'escucha', 'escuchamos', 'escuchan']},
  { e: 'expect', s: 'esperar', c: ['espero', 'esperas', 'espera', 'esperamos', 'esperan'] },
  { e: 'study', s: 'estudiar', c: ['estudio', 'estudias', 'estudia', 'estudiamos', 'estudian']},
  { e: 'shout', s: 'gritar', c: ['grito', 'gritas', 'grita', 'gritamos', 'gritan'] },
  { e: 'talk', s: 'hablar', c: ['hablo', 'hablas', 'habla', 'hablamos', 'hablan'] },
  { e: 'wash', s: 'lavar', c: ['lavo', 'lavas', 'lava', 'lavamos', 'lavan'] },
  { e: 'read', s: 'leer', c: ['leo', 'lees', 'lee', 'leemos', 'leen'] },
  { e: 'cry', s: 'llorar', c: ['lloro', 'lloras', 'llora', 'lloramos', 'lloran'] },
  { e: 'look', s: 'mirar', c: ['miro', 'miras', 'mira', 'miramos', 'miran'] },
  { e: 'swim', s: 'nadar', c: ['nado', 'nadas', 'nada', 'nadamos', 'nadan'] },
  { e: 'organize', s: 'organizar', c: ['organizo', 'organizas', 'organizamos', 'organizan'] },
  { e: 'comb', s: 'peinar', c: ['peino', 'peinas', 'peina', 'peinamos', 'peinan'] },
  { e: 'paint', s: 'pintar', c: ['pinto', 'pintas', 'pinta', 'pintamos', 'pintan'] },
  { e: 'spend (time)', s: 'pasar', c: ['paso', 'pasas', 'pasa', 'pasamos', 'pasan'] },
  { e: 'practice', s: 'practicar', c: ['practico', 'practicas', 'practica', 'practicamos', 'practican'] },
  { e: 'prepare', s: 'preparar', c: ['preparo', 'preparas', 'prepara', 'preparamos', 'preparan'] },
  { e: 'turn on', s: 'prender', c: ['prendo', 'prendes', 'prende', 'prendemos', 'prenden'] },
  { e: 'give away', s: 'regalar', c: ['regalo', 'regalas', 'regala', 'regalamos', 'regalan'] },
  { e: 'return', s: 'regresar', c: ['regreso', 'regresas', 'regresa', 'regresamos', 'regresan']},
  { e: 'tear', s: 'romper', c: ['rompo', 'rompes', 'rompe', 'rompemos', 'rompen'] },
  { e: 'take out', s: 'sacar', c: ['saco', 'sacas', 'saca', 'sacamos', 'sacan'] },
  { e: 'jump', s: 'saltar', c: ['salto', 'saltas', 'salta', 'saltamos', 'saltan'] },
  { e: 'greet', s: 'saludar', c: ['saludo', 'saludas', 'saluda', 'saludamos', 'saludan'] },
  { e: 'blow', s: 'soplar', c: ['soplo', 'soplas', 'sopla', 'soplamos', 'soplan'] },
  { e: 'touch (or play an instrument)', s: 'tocar', c: ['toco', 'tocas', 'toca', 'tocamos', 'tocan'] },
  { e: 'take / drink', s: 'tomar', c: ['tomo', 'tomas', 'toma', 'tomamos', 'toman'] },
  { e: 'work', s: 'trabajar', c: ['trabajo', 'trabajas', 'trabaja', 'trabajamos', 'trabajan'] },
  { e: 'visit', s: 'visitar', c: ['visito', 'visitas', 'visita', 'visitamos', 'visitan'] },
];
