const thanksgiving = [
  { e: 'apple', s: 'manzana', g: 'f' },
  { e: 'turkey', s: 'pavo', g: 'm' },
  { e: 'corn', s: 'maíz', g: 'm' },
  { e: 'vegetables', s: 'legumbres', g: 'm', p: true },
  { e: 'meat sauce', s: 'salsa de carne', g: 'f' },
  { e: 'stuffing', s: 'relleno', g: 'm' },
  { e: 'mashed potatoes', s: 'puré de papas', g: 'm' },
  { e: 'apple pie', s: 'torta de manzana', g: 'f' },
  { e: 'pumpkin pie', s: 'torta de calbaza', g: 'f' },
  { e: 'dinner', s: 'cena', g: 'f' },
  { e: 'rolls', s: 'panecillos', g: 'm' },
];

const stemChangingVerbs = [
  { e: 'close', s: 'cerrar', c: ['cierro', 'cierras', 'cierra', 'ceramos', 'cierran'] },
  { e: 'say', s: 'decir', c: ['digo', 'dices', 'dice', 'decimos', 'dicen'] },
  { e: 'sleep', s: 'dormir', c: ['duermo', 'duermes', 'duerme', 'dormimos', 'duermen'] },
  { e: 'bite', s: 'morder', c: ['muerdo', 'muerdes', 'muerde', 'mordemos', 'muerden'] },
  { e: 'plan', s: 'pensar', c: ['pienso', 'piensas', 'piensa', 'pensamos', 'piensan'] },
  { e: 'be able', s: 'poder', c: ['puedo', 'puedes', 'puede', 'podemos', 'pueden'] },
  { e: 'play', s: 'jugar', c: ['juego', 'juegas', 'juega', 'jugamos', 'juegan'] },
  { e: 'want', s: 'querer', c: ['quiero', 'quieres', 'quiere', 'queremos', 'quieren'] },
  { e: 'feel', s: 'sentir', c: ['siento', 'sientes', 'siente', 'sentimos', 'sienten'] },
  { e: 'come', s: 'venir', c: ['vengo', 'vienes', 'viene', 'venimos', 'vienen'] },
];

const irregularVerbs = [
  { e: 'fall', s: 'caer', c: ['caigo', 'caes', 'cae', 'caemos', 'caen'] },
  { e: 'give', s: 'dar', c: ['doy', 'das', 'da', 'damos', 'dan'] },
  { e: 'do', s: 'hacer', c: ['hago', 'haces', 'hace', 'hacemos', 'hacen'] },
  { e: 'go', s: 'ir', c: ['voy', 'vas', 'va', 'vamos', 'van'] },
  { e: 'put', s: 'poner', c: ['pongo', 'pones', 'pone', 'ponemos', 'ponen'] },
  { e: 'know / taste', s: 'sabor', c: ['sé', 'sabes', 'sabe', 'sabemos', 'saben'] },
  { e: 'go out', s: 'salir', c: ['salgo', 'sales', 'sale', 'salimos', 'salen'] },
  { e: 'bring', s: 'traer', c: ['traigo', 'traes', 'trae', 'traemos', 'traen'] },
  { e: 'see', s: 'ver', c: ['veo', 'ves', 've', 'vemos', 'ven'] },
];

const standardVerbs = [
  { e: 'open', s: 'abrir', c: ['abro', 'abres', 'abre', 'abremos', 'abren'] },
  { e: 'finish', s: 'acabar', c: ['acabo', 'acabas', 'acaba', 'acabamos', 'acaban'] },
  { e: 'dance', s: 'bailar', c: ['bailo', 'bailas', 'baila', 'bailamos', 'bailan'] },
  { e: 'sing', s: 'cantar', c: ['canto', 'cantas', 'canta', 'cantamos', 'cantan'] },
  { e: 'eat', s: 'comer', c: ['como', 'comes', 'come', 'comemos', 'comen'] },
  { e: 'buy', s: 'comprar', c: ['compro', 'compras', 'compra', 'compramos', 'compran'] },
  { e: 'rest', s: 'descansar', c: ['descanso', 'descansas', 'descansa', 'descansamos', 'descansan'] },
  { e: 'visit', s: 'visitar', c: ['visito', 'visitas', 'visita', 'visitamos', 'visitan'] },
  { e: 'help', s: 'ayudar', c: ['ayudo', 'ayudas', 'ayuda', 'ayudamos', 'ayudan'] },
  { e: 'kiss', s: 'besar', c: ['beso', 'besas', 'besa', 'besamos', 'besan']},
  { e: 'look for', s: 'buscar', c: ['busco', 'buscas', 'busca', 'buscamos', 'buscan'] },
  { e: 'walk', s: 'caminar', c: ['camino', 'caminas', 'camina', 'caminamos', 'caminan'] },
  { e: 'sing', s: 'cantar', c: ['canto', 'cantas', 'canta', 'cantamos', 'cantan'] },
  { e: 'cook', s: 'cocinar', c: ['cocino', 'cocinas', 'cocina', 'cocinamos', 'cocinan'] },
  { e: 'owe', s: 'deber', c: ['debo', 'debes', 'debe', 'debemos', 'deben'] },
  { e: 'draw', s: 'dibujar', c: ['dibujo', 'dibujas', 'dibuja', 'dibujamos', 'dibujan'] },
  { e: 'enter', s: 'entrar', c: ['entro', 'entras', 'entra', 'entramos', 'entran'] },
  { e: 'hide', s: 'esconder', c: ['escondo', 'escondes', 'esconde', 'escondemos', 'esconden'] },
  { e: 'expect', s: 'esperar', c: ['espero', 'esperas', 'espera', 'esperamos', 'esperan'] },
  { e: 'shout', s: 'gritar', c: ['grito', 'gritas', 'grita', 'gritamos', 'gritan'] },
  { e: 'run', s: 'correr', c: ['corro', 'corres', 'corre', 'corremos', 'corren'] },
  { e: 'organize', s: 'organizar', c: ['organizo', 'organizas', 'organizamos', 'organizan'] },
  { e: 'wash', s: 'lavar', c: ['lavo', 'lavas', 'lava', 'lavamos', 'lavan'] },
  { e: 'read', s: 'leer', c: ['leo', 'lees', 'lee', 'leemos', 'leen'] },
  { e: 'cry', s: 'llorar', c: ['lloro', 'lloras', 'llora', 'lloramos', 'lloran'] },
  { e: 'look', s: 'mirar', c: ['miro', 'miras', 'mira', 'miramos', 'miran'] },
  { e: 'swim', s: 'nadar', c: ['nado', 'nadas', 'nada', 'nadamos', 'nadan'] },
  { e: 'comb', s: 'peinar', c: ['peino', 'peinas', 'peina', 'peinamos', 'peinan'] },
  { e: 'turn on', s: 'prender', c: ['prendo', 'prendes', 'prende', 'prendemos', 'prenden'] },
  { e: 'give away', s: 'regalar', c: ['regalo', 'regalas', 'regala', 'regalamos', 'regalan'] },
  { e: 'tear', s: 'romper', c: ['rompo', 'rompes', 'rompe', 'rompemos', 'rompen'] },
  { e: 'jump', s: 'saltar', c: ['salto', 'saltas', 'salta', 'saltamos', 'saltan'] },
  { e: 'greet', s: 'saludar', c: ['saludo', 'saludas', 'saluda', 'saludamos', 'saludan'] },
  { e: 'blow', s: 'soplar', c: ['soplo', 'soplas', 'sopla', 'soplamos', 'soplan'] },
  { e: 'touch', s: 'tocar', c: ['toco', 'tocas', 'toca', 'tocamos', 'tocan'] },
];
