const thanksgiving = [
  { e: 'apple', s: 'manzana', g: 'f' },
  { e: 'turkey', s: 'pavo', g: 'm' },
  { e: 'corn', s: 'maíz', g: 'm' },
  { e: 'vegetables', s: 'legumbres', g: 'm', p: true },
  { e: 'meat sauce', s: 'salsa de carne', g: 'f' },
  { e: 'stuffing', s: 'relleno', g: 'm' },
  { e: 'mashed potatoes', s: 'puré de papas', g: 'm' },
  { e: 'apple pie', s: 'torta de manzana', g: 'f' },
  { e: 'pumpkin pie', s: 'torta de calbaza', g: 'f' },
  { e: 'dinner', s: 'cena', g: 'f' },
];

const stemChangingVerbs = [
  { e: 'plan', s: 'pensar', c: ['pienso', 'piensas', 'piensa', 'piensan', 'pensamos'] },
  { e: 'go', s: 'ir', c: ['voy', 'vas', 'va', 'van', 'vamos'] },
  { e: 'want', s: 'querer', c: ['quiero', 'quieres', 'quiere', 'quieren', 'queremos'] },
  { e: 'sleep', s: 'dormir', c: ['duermo', 'duermes', 'duerme', 'duermen', 'dormemos'] },
];

const standardVerbs = [
  { e: 'open', s: 'abrir', c: ['abro', 'abres', 'abre', 'abren', 'abremos'] },
  { e: 'dance', s: 'bailar', c: ['bailo', 'bailas', 'baila', 'bailan', 'bailamos'] },
  { e: 'sing', s: 'cantar', c: ['canto', 'cantas', 'canta', 'cantan', 'cantamos'] },
  { e: 'eat', s: 'comer', c: ['como', 'comes', 'come', 'comen', 'comemos'] },
  { e: 'buy', s: 'comprar', c: ['compro', 'compras', 'compra', 'compran', 'compramos'] },
  { e: 'say', s: 'decir', c: ['digo', 'dices', 'dice', 'dicen', 'dicemos'] },
  { e: 'do', s: 'hacer', c: ['hago', 'haces', 'hace', 'hacen', 'hacemos'] },
  { e: 'visit', s: 'visitar', c: ['visito', 'visitas', 'visita', 'visitan', 'visitamos'] },
  { e: 'rest', s: 'descansar' },
  { e: 'finish', s: 'acabar' },
  { e: 'help', s: 'ayudar' },
  { e: 'dance', s: 'bailar' },
  { e: 'kiss', s: 'besar' },
  { e: 'look for', s: 'buscar' },
  { e: 'fall', s: 'caer' },
  { e: 'walk', s: 'caminar' },
  { e: 'sing', s: 'cantar' },
  { e: 'close', s: 'cerrar' },
  { e: 'cook', s: 'cocinar' },
  { e: 'cut', s: 'correr' },
  { e: 'give', s: 'dar' },
  { e: 'owe', s: 'debar' },
  { e: 'say', s: 'decir' },
  { e: 'draw', s: 'dibujar' },
  { e: 'sleep', s: 'dormir' },
  { e: 'enter', s: 'entrar' },
  { e: 'hide', s: 'escondar' },
  { e: 'expect', s: 'esperar' },
  { e: 'shout', s: 'gritar' },
  { e: 'run', s: 'correr' },
  { e: 'organize', s: 'organizar' },
  { e: 'play', s: 'jugar' },
  { e: 'wash', s: 'lavar' },
  { e: 'read', s: 'leer' },
  { e: 'cry', s: 'llorar' },
  { e: 'look', s: 'mirar' },
  { e: 'bite', s: 'mordar' },
  { e: 'swim', s: 'nadar' },
  { e: 'comb', s: 'peinar' },
  { e: 'be able', s: 'podar' },
  { e: 'put', s: 'poner' },
  { e: 'turn on', s: 'prender' },
  { e: 'give away', s: 'regalar' },
  { e: 'tear', s: 'romplar' },
  { e: 'taste', s: 'sabor' },
  { e: 'go out', s: 'salir' },
  { e: 'jump', s: 'saltar' },
  { e: 'greet', s: 'saludar' },
  { e: 'feel', s: 'sentir' },
  { e: 'blow', s: 'soplar' },
  { e: 'touch', s: 'tocar' },
  { e: 'bring', s: 'traer' },
  { e: 'come', s: 'venir' },
  { e: 'see', s: 'ver' },
];
